export { default as SvgIcon } from './SvgIcon.vue'
export { default as UiLoader } from './Loader.vue'
export { default as UiButton } from './Button.vue'
export { default as UiInput } from './Input.vue'
export { default as UiModal } from './Modal.vue'
